#! /bin/sh
# /etc/init.d/rpotter-startup 

### BEGIN INIT INFO
# Provides:          rpotter
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start Raspberry Potter and pigpio at boot
# Description:       A simple script based on a script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here
pigpiod
modprobe bcm2835-v4l2

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting rpotter"
    # run application you want to start
    python /home/pi/rpotter.py
    ;;
  stop)
    echo "Stopping rpotter"
    # kill application you want to stop
    killall rpotter
    ;;
  *)
    echo "Usage: /etc/init.d/rpotter-startup {start|stop}"
    exit 1
    ;;
esac

exit 0
